
find_package(OpenAL REQUIRED MODULE)
find_package(PhysFS REQUIRED MODULE)
find_package(SDL2 REQUIRED MODULE)
find_package(SDL2_image REQUIRED MODULE)
find_package(SDL2_mixer REQUIRED MODULE)
find_package(SDL2_ttf REQUIRED MODULE)
find_package(OpenGL REQUIRED MODULE)
find_package(GLEW REQUIRED MODULE)
find_package(GLM REQUIRED MODULE)
find_package(TinyXML2 REQUIRED MODULE)
